asset_pipeline:
  revisioning:
    enable: true
    exclude: ['sitemap.xml', '*.json']
  clean_css:
    enable: true
  uglify_js:
    enable: true
  imagemin:
    enable: true
  html_minifier:
    enable: true